
/*
 * Copyright/Licensing information.
 */

/* inclusion guard */
#ifndef __VIEWER_GREEN_H__
#define __VIEWER_GREEN_H__

#include "viewer-file.h"
#include <glib-object.h>
/*
 * Potentially, include other headers on which this header depends.
 */

G_BEGIN_DECLS

/*
 * Type declaration.
 */
#define VIEWER_TYPE_GREEN viewer_green_get_type() /* defined by the G_DECLARE... macro below */
/*
   viewer - module
   green - class

   the name viewer_green_get_type is generated by the macro G_DECLARE.. by concaten
*/
G_DECLARE_DERIVABLE_TYPE (ViewerGreen, viewer_green, VIEWER, GREEN, ViewerFile)

struct _ViewerGreenClass
{
  GObjectClass parent_class;


  void (* open) (ViewerFile  *file,
                 GError     **error);
  void (* make_it_green) (void);


  /* Padding to allow adding up to 12 new virtual functions without
   * breaking ABI. */
  gpointer padding[12];
};

/*
 * Method definitions.
 */
ViewerGreen *viewer_green_new (void);

// Inherit from ViewerFile
// void viewer_file_open(ViewerGreen *self, GError **error);
void viewer_make_it_green(ViewerGreen *self);

G_END_DECLS

#endif /* __VIEWER_FILE_H__ */
